# Generated by Django 4.2.16 on 2024-10-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algelabApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='github_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
